name: Proof HTML
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: anishathalye/proof-html@v1.1.0
        with:
          directory: ./

# You may pin to the exact commit or the version.
# uses: anishathalye/proof-html@acec311c40ea13c9ffa6490e77ac67f52594f403
# uses: anishathalye/proof-html@v2.2.2
# with:
# The directory to scan
#     directory: 
# Validate HTML
#     check_html: # optional
# Validate CSS
#     check_css: # optional
# Regex of HTML/CSS validator errors to ignore
#     validator_ignore: # optional
# Check whether external anchors exist
#     check_external_hash: # optional
# Check images and URLs in Open Graph metadata
#     check_opengraph: # optional
# Check whether favicons are valid
#     check_favicon: # optional
# Allow images with empty alt tags
#     ignore_empty_alt: # optional
# Allow images with missing alt tags
#     ignore_missing_alt: # optional
# Allow anchors with missing href tags
#     allow_missing_href: # optional
# Require that links use HTTPS
#     enforce_https: # optional
# JSON-encoded map of domains to authorization tokens
#     tokens: # optional
# JSON-encoded map of URL rewrite rules
#     swap_urls: # optional
# Maximum number of concurrent requests
#     max_concurrency: # optional
# HTTP connection timeout
#     connect_timeout: # optional
# HTTP request timeout
#     timeout: # optional
# Disables the external link checker
#     disable_external: # optional
# Newline-separated list of URLs to ignore
#     ignore_url: # optional
# Newline-separated list of URL regexes to ignore
#    ignore_url_re: # optional
# Number of times to retry checking links
#   retries: # optional